# Generated by Django 5.0.1 on 2024-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityhospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='id',
        ),
        migrations.AlterField(
            model_name='departments',
            name='dep_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
